// <auto-generated />
using EF.App;
using EF.Lib;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EF.App.Migrations.MySqlServerMigrations
{
    [DbContext(typeof(MySQLDataBase))]
    partial class MySQLDataBaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.15");

            modelBuilder.Entity("EF.Model.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Creator")
                        .HasColumnType("text")
                        .HasColumnName("creator");

                    b.Property<string>("DateOfRelease")
                        .HasColumnType("text")
                        .HasColumnName("date_of_release");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Style")
                        .HasColumnType("text")
                        .HasColumnName("style");

                    b.HasKey("Id");

                    b.ToTable("TabGames");
                });
#pragma warning restore 612, 618
        }
    }
}
